name: Blueprints  
on: [push]
jobs:
  deploy_source:
    name: Deploy API Using Lambda
    strategy:
      matrix:
        node-version: [12.x]
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install and build
        run: |
          npm ci
          npm run build --if-present
        env:
          CI: true
          
      # Videos
      - name: /videos get lambda deploy zip
        uses: kinlane/blueprints@main
        with:
            args: zip -qq -r m-s-video-g.zip /videos/get/index.js node_modules
      - name: blueprints get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: $ secrets.AWS_ACCESS_KEY_ID
            aws_secret_access_key: $ secrets.AWS_SECRET_ACCESS_KEY
            aws_region: us-east-1
            function_name: m-s-video-g
            zip_file: m-s-video-g.zip
      - name: /videos post lambda deploy zip
        uses: kinlane/blueprints@main
        with:
            args: zip -qq -r m-s-video-g-po.zip /videos/post/index.js node_modules
      - name: blueprints get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: $ secrets.AWS_ACCESS_KEY_ID
            aws_secret_access_key: $ secrets.AWS_SECRET_ACCESS_KEY
            aws_region: us-east-1
            function_name: m-s-video-g-po
            zip_file: m-s-video-g-po.zip
      - name: /videos/{video_id} get lambda deploy zip
        uses: kinlane/blueprints@main
        with:
            args: zip -qq -r m-s-videos-video-g.zip /videos/video_id/get/index.js node_modules
      - name: blueprints get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: $ secrets.AWS_ACCESS_KEY_ID
            aws_secret_access_key: $ secrets.AWS_SECRET_ACCESS_KEY
            aws_region: us-east-1
            function_name: m-s-videos-video-g
            zip_file: m-s-videos-video-g.zip
      - name: /videos/{video_id} put lambda deploy zip
        uses: kinlane/blueprints@main
        with:
            args: zip -qq -r m-s-videos-video-g-pu.zip /videos/video_id/put/index.js node_modules
      - name: blueprints get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: $ secrets.AWS_ACCESS_KEY_ID
            aws_secret_access_key: $ secrets.AWS_SECRET_ACCESS_KEY
            aws_region: us-east-1
            function_name: m-s-videos-video-g-pu
            zip_file: m-s-videos-video-g-pu.zip
      - name: /videos/{video_id} delete lambda deploy zip
        uses: kinlane/blueprints@main
        with:
            args: zip -qq -r  m-s-videos-video-g-pu-d.zip /videos/video_id/delete/index.js node_modules
      - name: blueprints get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: $ secrets.AWS_ACCESS_KEY_ID
            aws_secret_access_key: $ secrets.AWS_SECRET_ACCESS_KEY
            aws_region: us-east-1
            function_name:  m-s-videos-video-g-pu-d
            zip_file:  m-s-videos-video-g-pu-d.zip      
 