name: Videos  
on: [push]
jobs:
  deploy_source:
    name: Deploy API Using Lambda
    strategy:
      matrix:
        node-version: [12.x]
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install and build
        run: |
          npm ci
          npm run build --if-present
        env:
          CI: true
          
      # Videos
      - name: /videos get lambda deploy zip
        uses: postman-open-technologies/videos@main
        with:
            args: zip -qq -r m-s-video-g.zip videos/get/index.js node_modules
      - name: videos get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-west-1
            function_name: m-s-video-g
            zip_file: m-s-video-g.zip
      - name: /videos post lambda deploy zip
        uses: postman-open-technologies/videos@main
        with:
            args: zip -qq -r m-s-video-po.zip videos/post/index.js node_modules
      - name: videos get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-west-1
            function_name: m-s-video-po
            zip_file: m-s-video-po.zip
      - name: /videos/{video_id} get lambda deploy zip
        uses: postman-open-technologies/videos@main
        with:
            args: zip -qq -r m-s-videos-video-g.zip videos/video_id/get/index.js node_modules
      - name: videos get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-west-1
            function_name: m-s-videos-video-g
            zip_file: m-s-videos-video-g.zip
      - name: /videos/{video_id} put lambda deploy zip
        uses: postman-open-technologies/videos@main
        with:
            args: zip -qq -r m-s-videos-video-pu.zip videos/video_id/put/index.js node_modules
      - name: videos get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-west-1
            function_name: m-s-videos-video-pu
            zip_file: m-s-videos-video-pu.zip
      - name: /videos/{video_id} delete lambda deploy zip
        uses: postman-open-technologies/videos@main
        with:
            args: zip -qq -r  m-s-videos-video-d.zip videos/video_id/delete/index.js node_modules
      - name: videos get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-west-1
            function_name:  m-s-videos-video-d
            zip_file:  m-s-videos-video-d.zip      
      - name: /videos/{video_id}/tags get lambda deploy zip
        uses: postman-open-technologies/videos@main
        with:
            args: zip -qq -r m-s-videos-video-tags-g.zip videos/video_id/tags/get/index.js node_modules
      - name: videos get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-west-1
            function_name: m-s-videos-video-tags-g
            zip_file: m-s-videos-video-tags-g.zip
      - name: /videos/{video_id}/tags post lambda deploy zip
        uses: postman-open-technologies/videos@main
        with:
            args: zip -qq -r m-s-videos-video-tags-po.zip videos/video_id/tags/post/index.js node_modules
      - name: videos get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-west-1
            function_name: m-s-videos-video-tags-po
            zip_file: m-s-videos-video-tags-po.zip
      - name: /videos/{video_id}/tags/{tag_id} delete lambda deploy zip
        uses: postman-open-technologies/videos@main
        with:
            args: zip -qq -r m-s-videos-video-tags-tag-d.zip videos/video_id/tags/tag_id/delete/index.js node_modules
      - name: videos get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-west-1
            function_name: m-s-videos-video-tags-tag-d
            zip_file: m-s-videos-video-tags-tag-d.zip            
 